### ISSUE TITLE
ERR_INVALIDCAPCMD isn't exposed

### ISSUE THREAD

**Issue by emersion** [go-irc/irc#77]
It's here: https://github.com/go-irc/irc/blob/master/utils/numerics.yml#L2379

I wonder if it's just missing "IRCv3" in the `origin` field? Where's the upstream for `numerics.yml`, should we fix it there?

**Comment by DanielOaks** [comment]
The upstream is over on defs here: https://defs.ircdocs.horse/defs/numerics.html#err-invalidcapcmd-410

(for refs I maintain the ircdocs stuff), we don't mark IRCv3 as the origin because technically they weren't the ones that introduced the numeric, it was done with the [Mitchell cap draft](https://tools.ietf.org/html/draft-mitchell-irc-capabilities-01)

**Comment by emersion** [comment]
Okay, thanks. Should we try to grep for "ircv3" in `information` to decide which numerics to expose then?

**Comment by belak** [comment]
I've updated the generation script to include items in the IRCv3 portion if ircv3 appears in the origin, contact, or information fields.

**Comment by emersion** [comment]
Thanks!

**Comment by belak** [comment]
I've also tagged v3.1.3 with all these numerics changes.
